name: Node.js CD

on: 
  push:
    branches: [ "main" ]

  jobs: 
    deploy:
      runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        name: Deploy to EC2
        uses: appleboy/ssh-action@v4
        with: 
          host: ${{ 13.60.18.157 }}
          username: ${{ ubuntu }}
          key: ${{ intermediate.pem }}
          port: 22
          script: |
            cd /home/ubuntu/node-app
            git pull origin main
            npm install
            pm2 restart node-app || pm2 start index.js --name node-app
        
